server:
  port: 8083

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/100points_enrollment}
    username: ${SPRING_DATASOURCE_USERNAME:100points}
    password: ${SPRING_DATASOURCE_PASSWORD:100points}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
