server:
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${ROUTE_AUTH_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
        - id: courses
          uri: ${ROUTE_COURSE_URI:http://localhost:8082}
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:5}
                redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST:10}
            - JwtAuthGatewayFilter
        - id: enrollments
          uri: ${ROUTE_ENROLL_URI:http://localhost:8083}
          predicates:
            - Path=/api/v1/enrollments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:5}
                redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST:10}
            - JwtAuthGatewayFilter
jwt:
  secret: ${JWT_SECRET:change-me}

management:
  endpoints:
    web:
      exposure:
        include: health,info
